name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@1.2.1
      with:
        # The root LaTeX file to be compiled
        root_file: paper.tex
        # The working directory for the LaTeX engine
        working_directory: # optional
        # The LaTeX engine to be invoked
        compiler: # optional, default is latexmk
        # Extra arguments to be passed to the LaTeX engine
        args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
        # [Deprecated] Install extra packages by tlmgr
        extra_packages: # optional
        # Install extra packages by apk
        extra_system_packages: # optional
    - name: Upload PDF File
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Upload final PDF file
        # Directory containing files to upload
        path: main.pdf
